GET http://localhost:8080 HTTP/1.1

###
GET http://localhost:8080/contacts HTTP/1.1

###
GET http://localhost:8080/contacts/6448eb2329aa4aaeaf5936f1 HTTP/1.1

###
GET http://localhost:8080/contacts/6448eb7529aa4aaeaf5a87ed HTTP/1.1

###
GET http://localhost:8080/contacts/6448eb8c29aa4aaeaf5ae6f0 HTTP/1.1

###
GET https://cse341-greenz.onrender.com