const swaggerAutogen = require('swagger-autogen')()

const doc = {
  info: {
    title: 'Emerald API',
    description: 'Documentation automatically generated by the <b>swagger-autogen<b> module'
  },
  host: 'localhost:8080',
  schemes: ['http'],
  produces: ['application/json'],
  consumes: ['application/json'],
  basePath: '/',
  tags: [
    {
      name: 'User',
      description: 'Endpoints'
    }
  ],
  securityDefinitions: {
    api_key: {
      type: 'apiKey',
      name: 'api_key',
      in: 'header'
    },
    petstore_auth: {
      type: 'oauth2',
      authorizationUrl: 'https://petstore.swagger.io/oauth/authorize',
      flow: 'implicit',
      scopes: {
        read_pets: 'read your pets',
        write_pets: 'modify pets in your account'
      }
    }
  },
  definitions: {
    User: {
      name: 'Emediong Edet',
      age: 29,
      parents: {
        father: 'Henry Edet',
        mother: 'Justina Edet'
      },
      diplomas: [
        {
          school: 'Brigham Young University',
          year: 2020,
          completed: true,
          internship: {
            hours: 290,
            location: 'XYZ Company'
          }
        }
      ]
    }
  },
  AddUser: {
    $name: 'Emediong Edet',
    $age: 29,
    about: ''
  }
}
const outputFile = './swagger-output.json'
const endpointsFiles = ['./endpoints.js']
// const endpointsFiles = ['./path/endpointsUser.js', './path/endpointsBook.js']

/* NOTE: if you use the express Router, you must pass in the
   'endpointsFiles' only the root file where the route starts,
   such as index.js, app.js, routes.js, ... */

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require('./routes/index') // Your project's root file
})
